/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xtra.visionxpress;

/**
 *
 * @author 35383
 */
public class MovieRentList extends javax.swing.JFrame {

    /**
     * Creates new form MenuShowMovies
     */
    public MovieRentList() {
        initComponents();
        setLocationRelativeTo( null );
        setDefaultCloseOperation(MovieRentList.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btntouchtorent = new javax.swing.JButton();
        btntouchtorent1 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTabListSelectedMovies = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Xtra-Vision Xpress renting a movie");

        btntouchtorent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntouchtorent.setText("Checkout");
        btntouchtorent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntouchtorentActionPerformed(evt);
            }
        });

        btntouchtorent1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntouchtorent1.setText("Cancel");
        btntouchtorent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntouchtorent1ActionPerformed(evt);
            }
        });

        jTabListSelectedMovies.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTabListSelectedMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabListSelectedMovies.setGridColor(new java.awt.Color(255, 255, 255));
        jTabListSelectedMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabListSelectedMoviesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabListSelectedMoviesMouseReleased(evt);
            }
        });
        jTabListSelectedMovies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabListSelectedMoviesKeyReleased(evt);
            }
        });
        jScrollPane9.setViewportView(jTabListSelectedMovies);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Press checkout to procede to payment");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Total     €");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btntouchtorent1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntouchtorent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btntouchtorent, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btntouchtorent1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntouchtorentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntouchtorentActionPerformed
        this.dispose();
        new MenuShowMovies().setVisible(true);
    }//GEN-LAST:event_btntouchtorentActionPerformed

    private void btntouchtorent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntouchtorent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntouchtorent1ActionPerformed

    private void jTabListSelectedMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabListSelectedMoviesMouseClicked
        // TODO add your handling code here:
//        clearTextRoutine();
//        DefaultTableModel model = (DefaultTableModel) jTabListSelectedMovies.getModel();
//        ResidentHistory resident = new ResidentHistory();
//        ResidentDAO daoR = new ResidentDAO();
//        List<ResidentHistory> residents = new ArrayList();
//
//        idResident = (int)jTabListSelectedMovies.getValueAt(jTabListSelectedMovies.getSelectedRow(), 0);
//
//        residents=daoR.searchResident(idResident);
//
//        for (ResidentHistory c : residents) {
//            jTextResidentNameRoutine.setText(c.getName());
//            caminho=(c.getPicture());
//        }
//
//        Image img = new ImageIcon(caminho).getImage().getScaledInstance(jLResidentPicRoutine.getWidth(),jLResidentPicRoutine.getHeight(), Image.SCALE_DEFAULT );
//        jLResidentPicRoutine.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_jTabListSelectedMoviesMouseClicked

    private void jTabListSelectedMoviesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabListSelectedMoviesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabListSelectedMoviesMouseReleased

    private void jTabListSelectedMoviesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabListSelectedMoviesKeyReleased
        // TODO add your handling code here:
//        clearTextRoutine();
//        DefaultTableModel model = (DefaultTableModel) jTabListSelectedMovies.getModel();
//        ResidentHistory resident = new ResidentHistory();
//        ResidentDAO daoR = new ResidentDAO();
//        List<ResidentHistory> residents = new ArrayList();
//
//        idResident = (int)jTabListSelectedMovies.getValueAt(jTabListSelectedMovies.getSelectedRow(), 0);
//
//        residents=daoR.searchResident(idResident);
//
//        for (ResidentHistory c : residents) {
//            jTextResidentNameRoutine.setText(c.getName());
//            caminho=(c.getPicture());
//        }
//
//        Image img = new ImageIcon(caminho).getImage().getScaledInstance(jLResidentPicRoutine.getWidth(),jLResidentPicRoutine.getHeight(), Image.SCALE_DEFAULT );
//        jLResidentPicRoutine.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_jTabListSelectedMoviesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieRentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieRentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieRentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieRentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieRentList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntouchtorent;
    private javax.swing.JButton btntouchtorent1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTabListSelectedMovies;
    // End of variables declaration//GEN-END:variables
}
